apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cassandra
    repo: oci://registry-1.docker.io/bitnamicharts
    version: 12.1.0
    includeCRDs: true
    releaseName: cassandra
    valuesFile: values.yaml