apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- traefik-ns.yaml


helmCharts:
  - name: traefik
    repo: https://helm.traefik.io/traefik
    version: 33.1.0-rc1
    releaseName: traefik
    namespace: traefik
    includeCRDs: true
    valuesFile: values.yaml