apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- flink-ns.yaml


# helmCharts:
#   - name: flink
#     repo: https://charts.bitnami.com/bitnami
#     version: 1.4.0
#     releaseName: flink
#     namespace: flink
#     valuesFile: values.yaml